server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    preferIpAddress: true

spring:
  application:
    name: service-registry
  boot:
    admin:
      client:
        url: ${BOOT_ADMIN_URL:http://localhost:9090}

debug: ${DEBUG:false}